
services:
  server1:
    image: ser1img
    expose:
      - "5010"  

  server2:
    image: ser2img
    expose:
      - "5001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
